ARG IRIS_SRC_IMAGE
ARG IRIS_APP_DIR
ARG IRIS_DB_DIR
ARG IRIS_INSTALL_SCRIPT
ARG IRIS_INSTALLER
ARG IRIS_TERMINAL
ARG IRIS_ZPM
ARG IRIS_DEMO1

FROM ${IRIS_SRC_IMAGE}

# Parameter has to be after FROM to access them aftter FROM
ARG IRIS_APP_DIR
ARG IRIS_DB_DIR
ARG IRIS_INSTALL_SCRIPT
ARG IRIS_INSTALLER
ARG IRIS_TERMINAL
ARG IRIS_ZPM
ARG IRIS_DEMO1

# RUN adduser ${ISC_PACKAGE_MGRUSER} root && adduser ${ISC_PACKAGE_MGRUSER} ${ISC_PACKAGE_MGRUSER}
USER root
# WORKDIR /data
# RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /data
WORKDIR ${IRIS_DB_DIR}

RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} ${IRIS_DB_DIR}
USER ${ISC_PACKAGE_MGRUSER}

WORKDIR ${IRIS_APP_DIR}
RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} ${IRIS_APP_DIR}
USER ${ISC_PACKAGE_MGRUSER}

COPY ${IRIS_INSTALL_SCRIPT} /tmp/irisinstall.script
COPY ${IRIS_INSTALLER} .
COPY ${IRIS_TERMINAL} WebTerminal.xml
COPY ${IRIS_ZPM} zpm.xml
COPY ${IRIS_DEMO1} .
COPY irisapp ./irisapp

# run iris and initial 
RUN iris start IRIS \
	&& iris session IRIS < /tmp/irisinstall.script
