version: '3.8'
services:
  iris:
    container_name: ${CONTAINER_NAME}
    init: true
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - IRIS_SRC_IMAGE=${IRIS_SRC_IMAGE}
        - IRIS_APP_DIR=${IRIS_APP_DIR}       
        - IRIS_DB_DIR=${IRIS_DB_DIR}
        - IRIS_INSTALL_SCRIPT=${IRIS_INSTALL_SCRIPT}
        - IRIS_INSTALLER=${IRIS_INSTALLER}
        - IRIS_TERMINAL=${IRIS_TERMINAL}
        - IRIS_ZPM=${IRIS_ZPM}
        - IRIS_DEMO1=${IRIS_DEMO1}       
    command: --check-caps false

    # restart: always
    ports:
    # 51773 is the superserver default port 
    - ${IRIS_HOST_PORT}:51773
    # 52773 is the webserver/management portal port
    - ${IRIS_WEBHOST_PORT}:52773

    #volumes:
    # Maps directory in container, named durable, to named volume defined below 
    #- data:/data
    # Mounts a local directory for passing in files and test scripts
    # - ./data:/irisapp
    #environment:
    # Uses ISC_DATA_DIRECTORY to place the durable %SYS in the named volume
    #- ISC_DATA_DIRECTORY=/data/irissys/
