ARG IMAGE=intersystems/iris-community:2022.1.0.209.0
FROM $IMAGE

# RUN adduser ${ISC_PACKAGE_MGRUSER} root && adduser ${ISC_PACKAGE_MGRUSER} ${ISC_PACKAGE_MGRUSER}
USER root
# WORKDIR /databases
# RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /data

WORKDIR /opt/irisapp
RUN chown ${ISC_PACKAGE_MGRUSER}:${ISC_PACKAGE_IRISGROUP} /opt/irisapp
USER ${ISC_PACKAGE_MGRUSER}

COPY Installer.cls .
COPY src /usr/irissys/mgr/src
COPY irisinstall.script /tmp/irisinstall.script

# run iris and initial 
RUN iris start IRIS \
	&& iris session IRIS < /tmp/irisinstall.script
