; run installer to create namespace
do $SYSTEM.OBJ.Load("/opt/irisapp/Installer.cls", "ck")
set sc = ##class(Docker.Installer).setup() 

;import webterminal
do $system.OBJ.Load("/opt/irisapp/WebTerminal-v4.9.5.xml","ck") 

;import zpm package tool
;do $system.OBJ.Load("/opt/irisapp/zpm-0.5.1.xml","ck") 

zn "%SYS"
Do ##class(Security.Users).UnExpireUserPasswords("*")

; call your initial methods here
halt
